global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['aws-beanstalk-pipeline-beanstalk-app-1:8081'] # Replace with your application's service name or IP address and port